# Stress Test FPR

This notebook tests whether the reduced fiducial-pair set is stable when the GST parameter vector changes.

It uses the same `smq2Q_XYICNOT` model as `GST_model.ipynb`. The reusable implementation lives in `near_minimal_fpr_reduction.py`; this notebook only calls functions from that file so it is easy to try different parameter vectors.

## Imports

In [13]:
import importlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import near_minimal_fpr_reduction as fpr_reduction
importlib.reload(fpr_reduction)

from near_minimal_fpr_reduction import (
    build_xyicnot_setup,
    jaccard_overlap,
    run_fpr_reduction,
    stress_test_random_parameter_vectors,
)

## Stress-Test Settings

`target` is the original pyGSTi target-model parameter vector, included only as a baseline. `random_1`, `random_2`, etc. are the sampled parameter vectors. `PARAMETER_SAMPLING_MODE` controls how random parameter vectors are generated. Use `"local_uniform"` for small bounded perturbations around the target vector, or `"global_uniform"` to draw each parameter directly between `GLOBAL_LOWER_BOUND` and `GLOBAL_UPPER_BOUND`.

In [18]:
NUM_RANDOM_VECTORS = 10

# Options: "twirled_derivative" or "probability_jacobian_proxy".
STAGE1_METHOD = "twirled_derivative"
COMMUTANT_REL_TOL = 1e-10

# Options: "local_uniform" or "global_uniform".
PARAMETER_SAMPLING_MODE = "global_uniform"

# Used only when PARAMETER_SAMPLING_MODE = "local_uniform".
PERTURBATION_SCALE = 1e-1

# Used only when PARAMETER_SAMPLING_MODE = "global_uniform".
GLOBAL_LOWER_BOUND = -np.pi
GLOBAL_UPPER_BOUND = np.pi

# Keep True if you want the original pyGSTi target vector as a baseline row.
# Set False if you want only random vectors sampled from the bounds.
INCLUDE_TARGET_BASELINE = False

RANDOM_SEED = 1234

# Set to an integer like 100 for a faster approximate debug run.
# Keep as None for the full proxy-rank run.
MAX_STAGE1_RANK_PER_GERM = None

# Set True if you want detailed per-germ progress printed.
VERBOSE = True

## Run FPR At Target And Random Parameter Vectors

This can take about 25-40 seconds per parameter vector in Docker.

In [19]:
runs, summary_df = stress_test_random_parameter_vectors(
    num_random_vectors=NUM_RANDOM_VECTORS,
    mode=PARAMETER_SAMPLING_MODE,
    perturbation_scale=PERTURBATION_SCALE,
    lower_bound=GLOBAL_LOWER_BOUND,
    upper_bound=GLOBAL_UPPER_BOUND,
    seed=RANDOM_SEED,
    include_target=INCLUDE_TARGET_BASELINE,
    stage1_method=STAGE1_METHOD,
    commutant_rel_tol=COMMUTANT_REL_TOL,
    max_stage1_rank_per_germ=MAX_STAGE1_RANK_PER_GERM,
    save_results=True,
    outdir="near_minimal_fpr_stress_results",
    verbose=VERBOSE,
)

summary_cols = [
    "label",
    "standard_circuits",
    "reduced_circuits",
    "circuits_removed",
    "reduction_fraction",
    "stage1_method",
    "stage1_global_rank",
    "stage1_proxy_global_rank",
    "total_selected_fiducial_pairs_across_germs",
    "all_stage2_ranks_complete",
    "pair_jaccard_vs_first_run",
    "sampling_mode",
    "perturbation_scale",
    "global_lower_bound",
    "global_upper_bound",
    "elapsed_seconds",
]

summary_df[summary_cols]

FPR reduction run: random_1
Model: smq2Q_XYICNOT
parameters: 1616
prep fiducials: 16
meas fiducials: 11
germs: 15
standard pyGSTi circuits: 8740
Stage 1 method: twirled_derivative
Stage 1 twirled_derivative germ 1/15: rank=16, elapsed=0.75s
Stage 1 twirled_derivative germ 2/15: rank=16, elapsed=0.72s
Stage 1 twirled_derivative germ 3/15: rank=16, elapsed=0.74s
Stage 1 twirled_derivative germ 4/15: rank=16, elapsed=0.62s
Stage 1 twirled_derivative germ 5/15: rank=16, elapsed=0.63s
Stage 1 twirled_derivative germ 6/15: rank=16, elapsed=0.63s
Stage 1 twirled_derivative germ 7/15: rank=16, elapsed=0.62s
Stage 1 twirled_derivative germ 8/15: rank=16, elapsed=0.61s
Stage 1 twirled_derivative germ 9/15: rank=16, elapsed=0.72s
Stage 1 twirled_derivative germ 10/15: rank=16, elapsed=0.72s
Stage 1 twirled_derivative germ 11/15: rank=16, elapsed=0.75s
Stage 1 twirled_derivative germ 12/15: rank=16, elapsed=1.29s
Stage 1 twirled_derivative germ 13/15: rank=16, elapsed=0.74s
Stage 1 twirled_derivative germ 14/15: rank=16, elapsed=0.90s
Stage 1 twirled_derivative germ 15/15: rank=16, elapsed=0.74s
Stage 1 concatenated J shape: (1616, 240)
Stage 1 selected global rank: 240
Stage 2 germ 1/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 2/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 3/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 4/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 5/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 6/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 7/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 8/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 9/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 10/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 11/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 12/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 13/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 14/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 15/15: r_g=16, pairs=4/176, rank=16/16

Reduction summary
label: random_1
modelpack: pygsti.modelpacks.smq2Q_XYICNOT
max_lengths: [1, 2, 4, 8, 16]
num_parameters: 1616
num_prep_fiducials: 16
num_meas_fiducials: 11
num_germs: 15
stage1_method: twirled_derivative
standard_circuits: 8740
reduced_circuits: 1103
circuits_removed: 7637
reduction_fraction: 0.8737986270022884
standard_probability_entries: 34960
reduced_probability_entries: 4412
stage1_global_J_shape: [1616, 240]
stage1_global_rank: 240
stage1_proxy_global_J_shape: [1616, 240]
stage1_proxy_global_rank: 240
total_selected_fiducial_pairs_across_germs: 60
total_candidate_fiducial_pairs_across_germs: 2640
all_stage2_ranks_complete: True
elapsed_seconds: 11.646546427997237
stage1_note: Stage 1 uses twirled germ derivatives when stage1_method='twirled_derivative'. Stage 2 uses probability Jacobians J_{g,c} and directional derivatives D_{g,c}=J_{g,c}W_g.
FPR reduction run: random_2
Model: smq2Q_XYICNOT
parameters: 1616
prep fiducials: 16
meas fiducials: 11
germs: 15
standard pyGSTi circuits: 8740
Stage 1 method: twirled_derivative

/usr/local/lib/python3.11/site-packages/pygsti/forwardsims/mapforwardsim.py:732: UserWarning: Generating dense process matrix representations of circuits or gates
can be inefficient and should be avoided for the purposes of forward
simulation/calculation of circuit outcome probability distributions
when using the MapForwardSimulator.
  _warnings.warn('Generating dense process matrix representations of circuits or gates \n'

Stage 1 twirled_derivative germ 1/15: rank=16, elapsed=1.18s
Stage 1 twirled_derivative germ 2/15: rank=16, elapsed=0.63s
Stage 1 twirled_derivative germ 3/15: rank=16, elapsed=0.73s
Stage 1 twirled_derivative germ 4/15: rank=16, elapsed=0.70s
Stage 1 twirled_derivative germ 5/15: rank=16, elapsed=0.66s
Stage 1 twirled_derivative germ 6/15: rank=16, elapsed=0.71s
Stage 1 twirled_derivative germ 7/15: rank=16, elapsed=0.69s
Stage 1 twirled_derivative germ 8/15: rank=16, elapsed=0.73s
Stage 1 twirled_derivative germ 9/15: rank=16, elapsed=0.80s
Stage 1 twirled_derivative germ 10/15: rank=16, elapsed=1.16s
Stage 1 twirled_derivative germ 11/15: rank=16, elapsed=0.75s
Stage 1 twirled_derivative germ 12/15: rank=16, elapsed=0.67s
Stage 1 twirled_derivative germ 13/15: rank=16, elapsed=0.70s
Stage 1 twirled_derivative germ 14/15: rank=16, elapsed=0.74s
Stage 1 twirled_derivative germ 15/15: rank=16, elapsed=0.65s
Stage 1 concatenated J shape: (1616, 240)
Stage 1 selected global rank: 240
Stage 2 germ 1/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 2/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 3/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 4/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 5/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 6/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 7/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 8/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 9/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 10/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 11/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 12/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 13/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 14/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 15/15: r_g=16, pairs=4/176, rank=16/16

Reduction summary
label: random_2
modelpack: pygsti.modelpacks.smq2Q_XYICNOT
max_lengths: [1, 2, 4, 8, 16]
num_parameters: 1616
num_prep_fiducials: 16
num_meas_fiducials: 11
num_germs: 15
stage1_method: twirled_derivative
standard_circuits: 8740
reduced_circuits: 1103
circuits_removed: 7637
reduction_fraction: 0.8737986270022884
standard_probability_entries: 34960
reduced_probability_entries: 4412
stage1_global_J_shape: [1616, 240]
stage1_global_rank: 240
stage1_proxy_global_J_shape: [1616, 240]
stage1_proxy_global_rank: 240
total_selected_fiducial_pairs_across_germs: 60
total_candidate_fiducial_pairs_across_germs: 2640
all_stage2_ranks_complete: True
elapsed_seconds: 11.984775444994739
stage1_note: Stage 1 uses twirled germ derivatives when stage1_method='twirled_derivative'. Stage 2 uses probability Jacobians J_{g,c} and directional derivatives D_{g,c}=J_{g,c}W_g.
FPR reduction run: random_3
Model: smq2Q_XYICNOT
parameters: 1616
prep fiducials: 16
meas fiducials: 11
germs: 15
standard pyGSTi circuits: 8740
Stage 1 method: twirled_derivative

/usr/local/lib/python3.11/site-packages/pygsti/forwardsims/mapforwardsim.py:732: UserWarning: Generating dense process matrix representations of circuits or gates
can be inefficient and should be avoided for the purposes of forward
simulation/calculation of circuit outcome probability distributions
when using the MapForwardSimulator.
  _warnings.warn('Generating dense process matrix representations of circuits or gates \n'

Stage 1 twirled_derivative germ 1/15: rank=16, elapsed=0.70s
Stage 1 twirled_derivative germ 2/15: rank=16, elapsed=0.72s
Stage 1 twirled_derivative germ 3/15: rank=16, elapsed=0.92s
Stage 1 twirled_derivative germ 4/15: rank=16, elapsed=0.72s
Stage 1 twirled_derivative germ 5/15: rank=16, elapsed=0.72s
Stage 1 twirled_derivative germ 6/15: rank=16, elapsed=1.01s
Stage 1 twirled_derivative germ 7/15: rank=16, elapsed=0.73s
Stage 1 twirled_derivative germ 8/15: rank=16, elapsed=0.70s
Stage 1 twirled_derivative germ 9/15: rank=16, elapsed=0.68s
Stage 1 twirled_derivative germ 10/15: rank=16, elapsed=0.70s
Stage 1 twirled_derivative germ 11/15: rank=16, elapsed=0.62s
Stage 1 twirled_derivative germ 12/15: rank=16, elapsed=1.30s
Stage 1 twirled_derivative germ 13/15: rank=16, elapsed=0.65s
Stage 1 twirled_derivative germ 14/15: rank=16, elapsed=0.80s
Stage 1 twirled_derivative germ 15/15: rank=16, elapsed=0.76s
Stage 1 concatenated J shape: (1616, 240)
Stage 1 selected global rank: 240
Stage 2 germ 1/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 2/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 3/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 4/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 5/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 6/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 7/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 8/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 9/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 10/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 11/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 12/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 13/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 14/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 15/15: r_g=16, pairs=4/176, rank=16/16

Reduction summary
label: random_3
modelpack: pygsti.modelpacks.smq2Q_XYICNOT
max_lengths: [1, 2, 4, 8, 16]
num_parameters: 1616
num_prep_fiducials: 16
num_meas_fiducials: 11
num_germs: 15
stage1_method: twirled_derivative
standard_circuits: 8740
reduced_circuits: 1103
circuits_removed: 7637
reduction_fraction: 0.8737986270022884
standard_probability_entries: 34960
reduced_probability_entries: 4412
stage1_global_J_shape: [1616, 240]
stage1_global_rank: 240
stage1_proxy_global_J_shape: [1616, 240]
stage1_proxy_global_rank: 240
total_selected_fiducial_pairs_across_germs: 60
total_candidate_fiducial_pairs_across_germs: 2640
all_stage2_ranks_complete: True
elapsed_seconds: 12.265090367000084
stage1_note: Stage 1 uses twirled germ derivatives when stage1_method='twirled_derivative'. Stage 2 uses probability Jacobians J_{g,c} and directional derivatives D_{g,c}=J_{g,c}W_g.
FPR reduction run: random_4
Model: smq2Q_XYICNOT
parameters: 1616
prep fiducials: 16
meas fiducials: 11
germs: 15
standard pyGSTi circuits: 8740
Stage 1 method: twirled_derivative

/usr/local/lib/python3.11/site-packages/pygsti/forwardsims/mapforwardsim.py:732: UserWarning: Generating dense process matrix representations of circuits or gates
can be inefficient and should be avoided for the purposes of forward
simulation/calculation of circuit outcome probability distributions
when using the MapForwardSimulator.
  _warnings.warn('Generating dense process matrix representations of circuits or gates \n'

Stage 1 twirled_derivative germ 1/15: rank=16, elapsed=0.66s
Stage 1 twirled_derivative germ 2/15: rank=16, elapsed=0.57s
Stage 1 twirled_derivative germ 3/15: rank=16, elapsed=1.00s
Stage 1 twirled_derivative germ 4/15: rank=16, elapsed=0.62s
Stage 1 twirled_derivative germ 5/15: rank=16, elapsed=0.71s
Stage 1 twirled_derivative germ 6/15: rank=16, elapsed=0.76s
Stage 1 twirled_derivative germ 7/15: rank=16, elapsed=0.64s
Stage 1 twirled_derivative germ 8/15: rank=16, elapsed=0.62s
Stage 1 twirled_derivative germ 9/15: rank=16, elapsed=0.77s
Stage 1 twirled_derivative germ 10/15: rank=16, elapsed=0.66s
Stage 1 twirled_derivative germ 11/15: rank=16, elapsed=0.64s
Stage 1 twirled_derivative germ 12/15: rank=16, elapsed=0.66s
Stage 1 twirled_derivative germ 13/15: rank=16, elapsed=0.74s
Stage 1 twirled_derivative germ 14/15: rank=16, elapsed=2.14s
Stage 1 twirled_derivative germ 15/15: rank=16, elapsed=1.70s
Stage 1 concatenated J shape: (1616, 240)
Stage 1 selected global rank: 240
Stage 2 germ 1/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 2/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 3/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 4/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 5/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 6/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 7/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 8/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 9/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 10/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 11/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 12/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 13/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 14/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 15/15: r_g=16, pairs=4/176, rank=16/16

Reduction summary
label: random_4
modelpack: pygsti.modelpacks.smq2Q_XYICNOT
max_lengths: [1, 2, 4, 8, 16]
num_parameters: 1616
num_prep_fiducials: 16
num_meas_fiducials: 11
num_germs: 15
stage1_method: twirled_derivative
standard_circuits: 8740
reduced_circuits: 1103
circuits_removed: 7637
reduction_fraction: 0.8737986270022884
standard_probability_entries: 34960
reduced_probability_entries: 4412
stage1_global_J_shape: [1616, 240]
stage1_global_rank: 240
stage1_proxy_global_J_shape: [1616, 240]
stage1_proxy_global_rank: 240
total_selected_fiducial_pairs_across_germs: 60
total_candidate_fiducial_pairs_across_germs: 2640
all_stage2_ranks_complete: True
elapsed_seconds: 13.54920120099996
stage1_note: Stage 1 uses twirled germ derivatives when stage1_method='twirled_derivative'. Stage 2 uses probability Jacobians J_{g,c} and directional derivatives D_{g,c}=J_{g,c}W_g.
FPR reduction run: random_5
Model: smq2Q_XYICNOT
parameters: 1616
prep fiducials: 16
meas fiducials: 11
germs: 15
standard pyGSTi circuits: 8740
Stage 1 method: twirled_derivative

/usr/local/lib/python3.11/site-packages/pygsti/forwardsims/mapforwardsim.py:732: UserWarning: Generating dense process matrix representations of circuits or gates
can be inefficient and should be avoided for the purposes of forward
simulation/calculation of circuit outcome probability distributions
when using the MapForwardSimulator.
  _warnings.warn('Generating dense process matrix representations of circuits or gates \n'

Stage 1 twirled_derivative germ 1/15: rank=16, elapsed=0.99s
Stage 1 twirled_derivative germ 2/15: rank=16, elapsed=0.70s
Stage 1 twirled_derivative germ 3/15: rank=16, elapsed=0.73s
Stage 1 twirled_derivative germ 4/15: rank=16, elapsed=0.70s
Stage 1 twirled_derivative germ 5/15: rank=16, elapsed=0.71s
Stage 1 twirled_derivative germ 6/15: rank=16, elapsed=0.71s
Stage 1 twirled_derivative germ 7/15: rank=16, elapsed=0.73s
Stage 1 twirled_derivative germ 8/15: rank=16, elapsed=0.66s
Stage 1 twirled_derivative germ 9/15: rank=16, elapsed=0.74s
Stage 1 twirled_derivative germ 10/15: rank=16, elapsed=0.76s
Stage 1 twirled_derivative germ 11/15: rank=16, elapsed=0.69s
Stage 1 twirled_derivative germ 12/15: rank=16, elapsed=0.73s
Stage 1 twirled_derivative germ 13/15: rank=16, elapsed=0.73s
Stage 1 twirled_derivative germ 14/15: rank=16, elapsed=1.12s
Stage 1 twirled_derivative germ 15/15: rank=16, elapsed=0.68s
Stage 1 concatenated J shape: (1616, 240)
Stage 1 selected global rank: 240
Stage 2 germ 1/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 2/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 3/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 4/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 5/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 6/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 7/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 8/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 9/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 10/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 11/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 12/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 13/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 14/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 15/15: r_g=16, pairs=4/176, rank=16/16

Reduction summary
label: random_5
modelpack: pygsti.modelpacks.smq2Q_XYICNOT
max_lengths: [1, 2, 4, 8, 16]
num_parameters: 1616
num_prep_fiducials: 16
num_meas_fiducials: 11
num_germs: 15
stage1_method: twirled_derivative
standard_circuits: 8740
reduced_circuits: 1103
circuits_removed: 7637
reduction_fraction: 0.8737986270022884
standard_probability_entries: 34960
reduced_probability_entries: 4412
stage1_global_J_shape: [1616, 240]
stage1_global_rank: 240
stage1_proxy_global_J_shape: [1616, 240]
stage1_proxy_global_rank: 240
total_selected_fiducial_pairs_across_germs: 60
total_candidate_fiducial_pairs_across_germs: 2640
all_stage2_ranks_complete: True
elapsed_seconds: 11.90449266500218
stage1_note: Stage 1 uses twirled germ derivatives when stage1_method='twirled_derivative'. Stage 2 uses probability Jacobians J_{g,c} and directional derivatives D_{g,c}=J_{g,c}W_g.
FPR reduction run: random_6
Model: smq2Q_XYICNOT
parameters: 1616
prep fiducials: 16
meas fiducials: 11
germs: 15
standard pyGSTi circuits: 8740
Stage 1 method: twirled_derivative

/usr/local/lib/python3.11/site-packages/pygsti/forwardsims/mapforwardsim.py:732: UserWarning: Generating dense process matrix representations of circuits or gates
can be inefficient and should be avoided for the purposes of forward
simulation/calculation of circuit outcome probability distributions
when using the MapForwardSimulator.
  _warnings.warn('Generating dense process matrix representations of circuits or gates \n'

Stage 1 twirled_derivative germ 1/15: rank=16, elapsed=0.60s
Stage 1 twirled_derivative germ 2/15: rank=16, elapsed=0.74s
Stage 1 twirled_derivative germ 3/15: rank=16, elapsed=0.74s
Stage 1 twirled_derivative germ 4/15: rank=16, elapsed=0.64s
Stage 1 twirled_derivative germ 5/15: rank=16, elapsed=1.42s
Stage 1 twirled_derivative germ 6/15: rank=16, elapsed=0.72s
Stage 1 twirled_derivative germ 7/15: rank=16, elapsed=0.79s
Stage 1 twirled_derivative germ 8/15: rank=16, elapsed=0.73s
Stage 1 twirled_derivative germ 9/15: rank=16, elapsed=0.72s
Stage 1 twirled_derivative germ 10/15: rank=16, elapsed=0.66s
Stage 1 twirled_derivative germ 11/15: rank=16, elapsed=0.74s
Stage 1 twirled_derivative germ 12/15: rank=16, elapsed=0.62s
Stage 1 twirled_derivative germ 13/15: rank=16, elapsed=0.67s
Stage 1 twirled_derivative germ 14/15: rank=16, elapsed=0.75s
Stage 1 twirled_derivative germ 15/15: rank=16, elapsed=0.67s
Stage 1 concatenated J shape: (1616, 240)
Stage 1 selected global rank: 240
Stage 2 germ 1/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 2/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 3/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 4/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 5/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 6/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 7/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 8/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 9/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 10/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 11/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 12/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 13/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 14/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 15/15: r_g=16, pairs=4/176, rank=16/16

Reduction summary
label: random_6
modelpack: pygsti.modelpacks.smq2Q_XYICNOT
max_lengths: [1, 2, 4, 8, 16]
num_parameters: 1616
num_prep_fiducials: 16
num_meas_fiducials: 11
num_germs: 15
stage1_method: twirled_derivative
standard_circuits: 8740
reduced_circuits: 1103
circuits_removed: 7637
reduction_fraction: 0.8737986270022884
standard_probability_entries: 34960
reduced_probability_entries: 4412
stage1_global_J_shape: [1616, 240]
stage1_global_rank: 240
stage1_proxy_global_J_shape: [1616, 240]
stage1_proxy_global_rank: 240
total_selected_fiducial_pairs_across_germs: 60
total_candidate_fiducial_pairs_across_germs: 2640
all_stage2_ranks_complete: True
elapsed_seconds: 11.682764062999922
stage1_note: Stage 1 uses twirled germ derivatives when stage1_method='twirled_derivative'. Stage 2 uses probability Jacobians J_{g,c} and directional derivatives D_{g,c}=J_{g,c}W_g.
FPR reduction run: random_7
Model: smq2Q_XYICNOT
parameters: 1616
prep fiducials: 16
meas fiducials: 11
germs: 15
standard pyGSTi circuits: 8740
Stage 1 method: twirled_derivative

/usr/local/lib/python3.11/site-packages/pygsti/forwardsims/mapforwardsim.py:732: UserWarning: Generating dense process matrix representations of circuits or gates
can be inefficient and should be avoided for the purposes of forward
simulation/calculation of circuit outcome probability distributions
when using the MapForwardSimulator.
  _warnings.warn('Generating dense process matrix representations of circuits or gates \n'

Stage 1 twirled_derivative germ 1/15: rank=16, elapsed=0.70s
Stage 1 twirled_derivative germ 2/15: rank=16, elapsed=0.72s
Stage 1 twirled_derivative germ 3/15: rank=16, elapsed=0.76s
Stage 1 twirled_derivative germ 4/15: rank=16, elapsed=0.83s
Stage 1 twirled_derivative germ 5/15: rank=16, elapsed=0.67s
Stage 1 twirled_derivative germ 6/15: rank=16, elapsed=0.73s
Stage 1 twirled_derivative germ 7/15: rank=16, elapsed=0.76s
Stage 1 twirled_derivative germ 8/15: rank=16, elapsed=0.69s
Stage 1 twirled_derivative germ 9/15: rank=16, elapsed=0.77s
Stage 1 twirled_derivative germ 10/15: rank=16, elapsed=0.57s
Stage 1 twirled_derivative germ 11/15: rank=16, elapsed=0.74s
Stage 1 twirled_derivative germ 12/15: rank=16, elapsed=0.83s
Stage 1 twirled_derivative germ 13/15: rank=16, elapsed=0.67s
Stage 1 twirled_derivative germ 14/15: rank=16, elapsed=0.76s
Stage 1 twirled_derivative germ 15/15: rank=16, elapsed=0.76s
Stage 1 concatenated J shape: (1616, 240)
Stage 1 selected global rank: 240
Stage 2 germ 1/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 2/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 3/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 4/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 5/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 6/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 7/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 8/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 9/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 10/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 11/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 12/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 13/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 14/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 15/15: r_g=16, pairs=4/176, rank=16/16

Reduction summary
label: random_7
modelpack: pygsti.modelpacks.smq2Q_XYICNOT
max_lengths: [1, 2, 4, 8, 16]
num_parameters: 1616
num_prep_fiducials: 16
num_meas_fiducials: 11
num_germs: 15
stage1_method: twirled_derivative
standard_circuits: 8740
reduced_circuits: 1103
circuits_removed: 7637
reduction_fraction: 0.8737986270022884
standard_probability_entries: 34960
reduced_probability_entries: 4412
stage1_global_J_shape: [1616, 240]
stage1_global_rank: 240
stage1_proxy_global_J_shape: [1616, 240]
stage1_proxy_global_rank: 240
total_selected_fiducial_pairs_across_germs: 60
total_candidate_fiducial_pairs_across_germs: 2640
all_stage2_ranks_complete: True
elapsed_seconds: 11.460394905006979
stage1_note: Stage 1 uses twirled germ derivatives when stage1_method='twirled_derivative'. Stage 2 uses probability Jacobians J_{g,c} and directional derivatives D_{g,c}=J_{g,c}W_g.
FPR reduction run: random_8
Model: smq2Q_XYICNOT
parameters: 1616
prep fiducials: 16
meas fiducials: 11
germs: 15
standard pyGSTi circuits: 8740
Stage 1 method: twirled_derivative

/usr/local/lib/python3.11/site-packages/pygsti/forwardsims/mapforwardsim.py:732: UserWarning: Generating dense process matrix representations of circuits or gates
can be inefficient and should be avoided for the purposes of forward
simulation/calculation of circuit outcome probability distributions
when using the MapForwardSimulator.
  _warnings.warn('Generating dense process matrix representations of circuits or gates \n'

Stage 1 twirled_derivative germ 1/15: rank=16, elapsed=0.66s
Stage 1 twirled_derivative germ 2/15: rank=16, elapsed=0.73s
Stage 1 twirled_derivative germ 3/15: rank=16, elapsed=0.67s
Stage 1 twirled_derivative germ 4/15: rank=16, elapsed=0.61s
Stage 1 twirled_derivative germ 5/15: rank=16, elapsed=0.71s
Stage 1 twirled_derivative germ 6/15: rank=16, elapsed=0.61s
Stage 1 twirled_derivative germ 7/15: rank=16, elapsed=0.87s
Stage 1 twirled_derivative germ 8/15: rank=16, elapsed=0.76s
Stage 1 twirled_derivative germ 9/15: rank=16, elapsed=0.79s
Stage 1 twirled_derivative germ 10/15: rank=16, elapsed=0.66s
Stage 1 twirled_derivative germ 11/15: rank=16, elapsed=1.02s
Stage 1 twirled_derivative germ 12/15: rank=16, elapsed=0.62s
Stage 1 twirled_derivative germ 13/15: rank=16, elapsed=0.67s
Stage 1 twirled_derivative germ 14/15: rank=16, elapsed=0.80s
Stage 1 twirled_derivative germ 15/15: rank=16, elapsed=0.71s
Stage 1 concatenated J shape: (1616, 240)
Stage 1 selected global rank: 240
Stage 2 germ 1/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 2/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 3/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 4/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 5/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 6/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 7/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 8/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 9/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 10/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 11/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 12/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 13/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 14/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 15/15: r_g=16, pairs=4/176, rank=16/16

Reduction summary
label: random_8
modelpack: pygsti.modelpacks.smq2Q_XYICNOT
max_lengths: [1, 2, 4, 8, 16]
num_parameters: 1616
num_prep_fiducials: 16
num_meas_fiducials: 11
num_germs: 15
stage1_method: twirled_derivative
standard_circuits: 8740
reduced_circuits: 1103
circuits_removed: 7637
reduction_fraction: 0.8737986270022884
standard_probability_entries: 34960
reduced_probability_entries: 4412
stage1_global_J_shape: [1616, 240]
stage1_global_rank: 240
stage1_proxy_global_J_shape: [1616, 240]
stage1_proxy_global_rank: 240
total_selected_fiducial_pairs_across_germs: 60
total_candidate_fiducial_pairs_across_germs: 2640
all_stage2_ranks_complete: True
elapsed_seconds: 11.375668462998874
stage1_note: Stage 1 uses twirled germ derivatives when stage1_method='twirled_derivative'. Stage 2 uses probability Jacobians J_{g,c} and directional derivatives D_{g,c}=J_{g,c}W_g.
FPR reduction run: random_9
Model: smq2Q_XYICNOT
parameters: 1616
prep fiducials: 16
meas fiducials: 11
germs: 15
standard pyGSTi circuits: 8740
Stage 1 method: twirled_derivative

/usr/local/lib/python3.11/site-packages/pygsti/forwardsims/mapforwardsim.py:732: UserWarning: Generating dense process matrix representations of circuits or gates
can be inefficient and should be avoided for the purposes of forward
simulation/calculation of circuit outcome probability distributions
when using the MapForwardSimulator.
  _warnings.warn('Generating dense process matrix representations of circuits or gates \n'

Stage 1 twirled_derivative germ 1/15: rank=16, elapsed=0.90s
Stage 1 twirled_derivative germ 2/15: rank=16, elapsed=0.59s
Stage 1 twirled_derivative germ 3/15: rank=16, elapsed=0.67s
Stage 1 twirled_derivative germ 4/15: rank=16, elapsed=0.59s
Stage 1 twirled_derivative germ 5/15: rank=16, elapsed=1.17s
Stage 1 twirled_derivative germ 6/15: rank=16, elapsed=1.29s
Stage 1 twirled_derivative germ 7/15: rank=16, elapsed=0.96s
Stage 1 twirled_derivative germ 8/15: rank=16, elapsed=0.75s
Stage 1 twirled_derivative germ 9/15: rank=16, elapsed=0.73s
Stage 1 twirled_derivative germ 10/15: rank=16, elapsed=0.70s
Stage 1 twirled_derivative germ 11/15: rank=16, elapsed=0.70s
Stage 1 twirled_derivative germ 12/15: rank=16, elapsed=0.76s
Stage 1 twirled_derivative germ 13/15: rank=16, elapsed=2.10s
Stage 1 twirled_derivative germ 14/15: rank=16, elapsed=1.70s
Stage 1 twirled_derivative germ 15/15: rank=16, elapsed=1.37s
Stage 1 concatenated J shape: (1616, 240)
Stage 1 selected global rank: 240
Stage 2 germ 1/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 2/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 3/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 4/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 5/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 6/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 7/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 8/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 9/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 10/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 11/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 12/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 13/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 14/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 15/15: r_g=16, pairs=4/176, rank=16/16

Reduction summary
label: random_9
modelpack: pygsti.modelpacks.smq2Q_XYICNOT
max_lengths: [1, 2, 4, 8, 16]
num_parameters: 1616
num_prep_fiducials: 16
num_meas_fiducials: 11
num_germs: 15
stage1_method: twirled_derivative
standard_circuits: 8740
reduced_circuits: 1103
circuits_removed: 7637
reduction_fraction: 0.8737986270022884
standard_probability_entries: 34960
reduced_probability_entries: 4412
stage1_global_J_shape: [1616, 240]
stage1_global_rank: 240
stage1_proxy_global_J_shape: [1616, 240]
stage1_proxy_global_rank: 240
total_selected_fiducial_pairs_across_germs: 60
total_candidate_fiducial_pairs_across_germs: 2640
all_stage2_ranks_complete: True
elapsed_seconds: 15.481726512000023
stage1_note: Stage 1 uses twirled germ derivatives when stage1_method='twirled_derivative'. Stage 2 uses probability Jacobians J_{g,c} and directional derivatives D_{g,c}=J_{g,c}W_g.
FPR reduction run: random_10
Model: smq2Q_XYICNOT
parameters: 1616
prep fiducials: 16
meas fiducials: 11
germs: 15
standard pyGSTi circuits: 8740
Stage 1 method: twirled_derivative

/usr/local/lib/python3.11/site-packages/pygsti/forwardsims/mapforwardsim.py:732: UserWarning: Generating dense process matrix representations of circuits or gates
can be inefficient and should be avoided for the purposes of forward
simulation/calculation of circuit outcome probability distributions
when using the MapForwardSimulator.
  _warnings.warn('Generating dense process matrix representations of circuits or gates \n'

Stage 1 twirled_derivative germ 1/15: rank=16, elapsed=0.61s
Stage 1 twirled_derivative germ 2/15: rank=16, elapsed=0.73s
Stage 1 twirled_derivative germ 3/15: rank=16, elapsed=0.72s
Stage 1 twirled_derivative germ 4/15: rank=16, elapsed=0.69s
Stage 1 twirled_derivative germ 5/15: rank=16, elapsed=0.72s
Stage 1 twirled_derivative germ 6/15: rank=16, elapsed=0.67s
Stage 1 twirled_derivative germ 7/15: rank=16, elapsed=0.77s
Stage 1 twirled_derivative germ 8/15: rank=16, elapsed=0.74s
Stage 1 twirled_derivative germ 9/15: rank=16, elapsed=0.67s
Stage 1 twirled_derivative germ 10/15: rank=16, elapsed=0.73s
Stage 1 twirled_derivative germ 11/15: rank=16, elapsed=0.67s
Stage 1 twirled_derivative germ 12/15: rank=16, elapsed=0.74s
Stage 1 twirled_derivative germ 13/15: rank=16, elapsed=0.74s
Stage 1 twirled_derivative germ 14/15: rank=16, elapsed=0.82s
Stage 1 twirled_derivative germ 15/15: rank=16, elapsed=1.35s
Stage 1 concatenated J shape: (1616, 240)
Stage 1 selected global rank: 240
Stage 2 germ 1/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 2/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 3/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 4/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 5/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 6/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 7/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 8/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 9/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 10/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 11/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 12/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 13/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 14/15: r_g=16, pairs=4/176, rank=16/16
Stage 2 germ 15/15: r_g=16, pairs=4/176, rank=16/16

Reduction summary
label: random_10
modelpack: pygsti.modelpacks.smq2Q_XYICNOT
max_lengths: [1, 2, 4, 8, 16]
num_parameters: 1616
num_prep_fiducials: 16
num_meas_fiducials: 11
num_germs: 15
stage1_method: twirled_derivative
standard_circuits: 8740
reduced_circuits: 1103
circuits_removed: 7637
reduction_fraction: 0.8737986270022884
standard_probability_entries: 34960
reduced_probability_entries: 4412
stage1_global_J_shape: [1616, 240]
stage1_global_rank: 240
stage1_proxy_global_J_shape: [1616, 240]
stage1_proxy_global_rank: 240
total_selected_fiducial_pairs_across_germs: 60
total_candidate_fiducial_pairs_across_germs: 2640
all_stage2_ranks_complete: True
elapsed_seconds: 11.844116549997125
stage1_note: Stage 1 uses twirled germ derivatives when stage1_method='twirled_derivative'. Stage 2 uses probability Jacobians J_{g,c} and directional derivatives D_{g,c}=J_{g,c}W_g.

,label,standard_circuits,reduced_circuits,circuits_removed,reduction_fraction,stage1_method,stage1_global_rank,stage1_proxy_global_rank,total_selected_fiducial_pairs_across_germs,all_stage2_ranks_complete,pair_jaccard_vs_first_run,sampling_mode,perturbation_scale,global_lower_bound,global_upper_bound,elapsed_seconds
0,random_1,8740,1103,7637,0.873799,twirled_derivative,240,240,60,True,1.000000,global_uniform,0.1,-3.141593,3.141593,11.646546
1,random_2,8740,1103,7637,0.873799,twirled_derivative,240,240,60,True,0.411765,global_uniform,0.1,-3.141593,3.141593,11.984775
2,random_3,8740,1103,7637,0.873799,twirled_derivative,240,240,60,True,0.445783,global_uniform,0.1,-3.141593,3.141593,12.265090
3,random_4,8740,1103,7637,0.873799,twirled_derivative,240,240,60,True,0.500000,global_uniform,0.1,-3.141593,3.141593,13.549201
4,random_5,8740,1103,7637,0.873799,twirled_derivative,240,240,60,True,0.411765,global_uniform,0.1,-3.141593,3.141593,11.904493
5,random_6,8740,1103,7637,0.873799,twirled_derivative,240,240,60,True,0.333333,global_uniform,0.1,-3.141593,3.141593,11.682764
6,random_7,8740,1103,7637,0.873799,twirled_derivative,240,240,60,True,0.428571,global_uniform,0.1,-3.141593,3.141593,11.460395
7,random_8,8740,1103,7637,0.873799,twirled_derivative,240,240,60,True,0.428571,global_uniform,0.1,-3.141593,3.141593,11.375668
8,random_9,8740,1103,7637,0.873799,twirled_derivative,240,240,60,True,0.463415,global_uniform,0.1,-3.141593,3.141593,15.481727
9,random_10,8740,1103,7637,0.873799,twirled_derivative,240,240,60,True,0.481481,global_uniform,0.1,-3.141593,3.141593,11.844117

In [24]:
# One-to-one comparison of selected fiducial pairs for one germ.
# Edit these two variables to choose which random runs and which germ to inspect.

DESIRED_RANDOM_LABELS = ["random_1", "random_2", "random_3", "random_4", "random_5", "random_6", "random_7"]
DESIRED_GERM_INDEX = 0

selected_pair_tables = []
for run in runs:
    label = run["summary"]["label"]
    if label not in DESIRED_RANDOM_LABELS:
        continue

    table = run["pair_records"].copy()
    table.insert(0, "label", label)
    selected_pair_tables.append(table)

if not selected_pair_tables:
    raise ValueError(
        f"No selected-pair data found for DESIRED_RANDOM_LABELS={DESIRED_RANDOM_LABELS}. "
        "Check that these labels exist in the current `runs` list."
    )

selected_pairs_for_desired_randoms = pd.concat(selected_pair_tables, ignore_index=True)
selected_pairs_for_desired_germ = selected_pairs_for_desired_randoms[
    selected_pairs_for_desired_randoms["germ_index"] == DESIRED_GERM_INDEX
].copy()

if selected_pairs_for_desired_germ.empty:
    raise ValueError(
        f"No selected pairs found for germ_index={DESIRED_GERM_INDEX} "
        f"inside DESIRED_RANDOM_LABELS={DESIRED_RANDOM_LABELS}."
    )

comparison_table = (
    selected_pairs_for_desired_germ
    .assign(selected=True)
    .pivot_table(
        index=["germ_index", "prep_fiducial_index", "meas_fiducial_index"],
        columns="label",
        values="selected",
        aggfunc="any",
        fill_value=False,
    )
    .reset_index()
)

# Keep the requested random-run order in the displayed columns.
comparison_table = comparison_table[
    ["germ_index", "prep_fiducial_index", "meas_fiducial_index"] + DESIRED_RANDOM_LABELS
]

for label in DESIRED_RANDOM_LABELS:
    comparison_table[label] = comparison_table[label].map({True: "yes", False: ""})

comparison_table = comparison_table.sort_values(
    ["prep_fiducial_index", "meas_fiducial_index"]
).reset_index(drop=True)

comparison_table.to_csv(
    f"near_minimal_fpr_stress_results/selected_pairs_germ_{DESIRED_GERM_INDEX}.csv",
    index=False,
)

comparison_table

label,germ_index,prep_fiducial_index,meas_fiducial_index,random_1,random_2,random_3,random_4,random_5,random_6,random_7
0,0,11,9,,,,,,yes,
1,0,13,9,,,,,yes,,
2,0,15,3,yes,yes,yes,yes,,yes,
3,0,15,6,yes,,yes,yes,yes,,
4,0,15,7,yes,yes,yes,,,yes,yes
5,0,15,8,,,,,yes,,yes
6,0,15,9,,yes,,yes,,yes,yes
7,0,15,10,yes,yes,yes,yes,yes,,yes